travis:
  secure:
    BINSTAR_TOKEN: cBbVgf5PifYgkKS+4GC/lzzrqzrB4m5cjwmtpHLn5dwgPIPrXr1E3YF18GEhEwWfij9fLKL9dZ60Mu3ayHoA3nkUcN7Sbg2M48InlG4RFNuRl1Wdi8tmL3xI0T2BeJMMo/vS8L+M+SBFhroCT9cnS6uYeDkiM7+pj6xxP022SviJ6TtCfYS/4BhnBgj/8nAcPuaAVR098w73E+bT75Glo/ocLZhlvo4RRTD586NPCx1v1y5/DyfWcJKt1iKmPJkD9h9xRQAjTddOsh+ubCeBDVl2Z3wZ1m/J6sen0zY5qQpcrwAzcnV+zVxqGomR9M0YFYrd7oAC5ElvzmDM4d467KocibkVSeOrsH0Kf9zsmb9diMsfNovdRgDh9tPhDLpdce3T+9qXgBlNlFI+4bDF/HNVuvehXZNe4VOq2/YYcl9+2t95Ubuzy+q+BFT5Qt2MdS45T7KUvriNNSefO5nHRW9AoZlTy0qdl03g7thZfo8/M+OIRCGJ69SJZhNIRAJgHOp7OT7XEQQUKX2knMgYjfqSp9ViFEcm88hcRWepUUEFK5jR/u+GhPOAT177QN3WQNinEyMYgtJPvDZkJ/44TRTJ/DURuzkhy9k3J8rd3wYOXV1F5om0GeDh1YuzC605kFcNU8sMY1wgf7B0JRE8U4f5cA6IYXZpS3ORD+U5P+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
