travis:
  secure:
    BINSTAR_TOKEN: lqj+yrHHgyCc2in8uQ9/Up6hr4JavdvZO+7DWsBmjho+pjvjprR21bx+ATzTten8SlL9egnMNeeDfcd1+643sx7Toftql1ul7rtbRyVqzmrRhJGqAtivbtyBWKTG2woXOHr7ZyfSsXhcLWQczMBV3eGnm4qn7glOWYSBiGhsJdqz4+qy0quDdrjuAb7+ZrmU90uFJp9te3wSR/nPSjVk90wdt0CzV/HHagQ45RrkOjYxZKknlnxj9FZLhMoVgaf2LgYxrLT0Hqeqf15xCYnjmckfcTf+FAmO7qud+a6LEHSDPok7nKR7XhjHjia0X1yyb0p4j5dj0fkZGg7DM42LfBr8Qh7FodY/AnecUofGUEm72sIl7qzxYL7iNKsso7Kkfln8R3SuQjTMKGCxIk00elMbOkN3w6Cdk6E3L7wES3N7FV3EH+oi3egkrWY/aBy1zlZzmyxV6GWL3RAr9UM1vs+p+7AfR8PUMdfGCmjUpDjBSvvfMGMfN0RJpV7VwdzbCjanNiWD56p1CLKU/jhA3nRobv3uRLpy5RP8fr0D+tKmVxzzLtUkvwpmrrSIOtAth0/CUP/FcXJ9n5k+p2E6xTneB9BupjJTDUhXs4ed8xhEvfGTjIL0zaXXvUM9L3KIB8YCYrlCySgBaWjUEbcbkvXH13vhwTJ1fjgLwyrJS/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
